/*
 * This file is part of Dominion Toolkit.
 *
 *  Dominion Toolkit is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Dominion Toolkit is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Dominion Toolkit.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.xilconic.dominiontoolkit.Activities.Randomizer;

/**
 * This exception indicates the randomizer was unable to generate
 * a set of cards to play with.
 * @author Bas des Bouvrie
 *
 */
public class RandomizationFailedException extends RuntimeException {
    // Autogenerated serial for serialization
    private static final long serialVersionUID = 1016268626101147105L;

    public RandomizationFailedException(){
        super();
    }
    
    public RandomizationFailedException(String message){
        super(message);
    }
}
